#!/usr/bin/env python3
from __future__ import annotations

import argparse
import html
import math
import re
import sys
from dataclasses import dataclass
from datetime import date
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT_DIR = ROOT / "content" / "posts"
BLOG_DIR = ROOT / "blog"
POSTS_DIR = BLOG_DIR / "posts"

SITE_TITLE = "Writing"
AUTHOR_NAME = "Pranav Pipariya"
SITE_DESCRIPTION = (
    "Longer notes on proof systems, interfaces, and the last mile between a "
    "correct idea and a usable tool."
)
GENERATED_COMMENT = (
    "<!-- Generated by scripts/blog.py. Edit content in content/posts/*.md. -->"
)


@dataclass
class Post:
    source_path: Path
    slug: str
    title: str
    summary: str
    body_markdown: str
    body_html: str
    date_value: date
    tags: list[str]
    featured: bool
    reading_time: int


@dataclass
class LandingProfile:
    avatar_src: str
    name: str
    tag_html: str


def load_landing_profile() -> LandingProfile:
    source = (ROOT / "index.html").read_text(encoding="utf-8")

    avatar_match = re.search(r'<img class="avatar" src="([^"]+)"', source)
    name_match = re.search(r'<h1 class="name">(.*?)</h1>', source, re.S)
    tag_match = re.search(r'<div class="tag">(.*?)</div>', source, re.S)

    avatar_src = (
        avatar_match.group(1).strip()
        if avatar_match
        else "https://i.pinimg.com/736x/16/b6/2a/16b62a70a9a8bc3fdc6e452abe73aa32.jpg"
    )
    name = (
        html.unescape(re.sub(r"\s+", " ", name_match.group(1)).strip())
        if name_match
        else AUTHOR_NAME
    )
    tag_html = (
        tag_match.group(1).strip()
        if tag_match
        else '& I like things you can <span class="ac">prove</span>, not things you can tune.'
    )

    return LandingProfile(avatar_src=avatar_src, name=name, tag_html=tag_html)


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "post"


def parse_bool(value: str) -> bool:
    return value.strip().lower() in {"1", "true", "yes", "on"}


def format_long_date(value: date) -> str:
    return f"{value.strftime('%B')} {value.day}, {value.year}"


def format_short_date(value: date) -> str:
    return f"{value.strftime('%b')} {value.day}, {value.year}"


def read_front_matter(text: str) -> tuple[dict[str, object], str]:
    lines = text.lstrip("\ufeff").splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text

    closing_index = None
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            closing_index = index
            break

    if closing_index is None:
        return {}, text

    front_matter: dict[str, object] = {}
    for raw_line in lines[1:closing_index]:
        line = raw_line.strip()
        if not line or ":" not in line:
            continue
        key, value = line.split(":", 1)
        parsed_key = key.strip().lower()
        parsed_value = value.strip()
        if parsed_key == "tags":
            front_matter[parsed_key] = [
                tag.strip() for tag in parsed_value.split(",") if tag.strip()
            ]
        elif parsed_key in {"featured", "draft"}:
            front_matter[parsed_key] = parse_bool(parsed_value)
        else:
            front_matter[parsed_key] = parsed_value

    body = "\n".join(lines[closing_index + 1 :]).strip()
    return front_matter, body


def strip_markdown(markdown: str) -> str:
    text = re.sub(r"```.*?```", " ", markdown, flags=re.S)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.M)
    text = re.sub(r"^\s*>\s?", "", text, flags=re.M)
    text = re.sub(r"^\s*[-*]\s+", "", text, flags=re.M)
    text = re.sub(r"^\s*\d+\.\s+", "", text, flags=re.M)
    text = re.sub(r"[*_~#>-]", "", text)
    return re.sub(r"\s+", " ", text).strip()


def trim_text(text: str, limit: int = 180) -> str:
    if len(text) <= limit:
        return text
    clipped = text[: limit + 1].rsplit(" ", 1)[0].strip()
    return f"{clipped}..."


def derive_summary(body_markdown: str) -> str:
    paragraphs = [chunk.strip() for chunk in body_markdown.split("\n\n") if chunk.strip()]
    if not paragraphs:
        return "A new note."
    return trim_text(strip_markdown(paragraphs[0]), 180)


def word_count(text: str) -> int:
    return len(re.findall(r"\b[\w'-]+\b", text))


def inline_arrow() -> str:
    return (
        '<svg class="arr" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
        'stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'
        '<line x1="7" y1="17" x2="17" y2="7"></line>'
        '<polyline points="7 7 17 7 17 17"></polyline>'
        "</svg>"
    )


def render_inline(text: str) -> str:
    pieces = re.split(r"(`[^`]+`)", text)
    rendered: list[str] = []

    for piece in pieces:
        if not piece:
            continue
        if piece.startswith("`") and piece.endswith("`"):
            rendered.append(f"<code>{html.escape(piece[1:-1])}</code>")
            continue

        tokens: dict[str, str] = {}

        def stash(content: str) -> str:
            token = f"__TOKEN_{len(tokens)}__"
            tokens[token] = content
            return token

        def replace_link(match: re.Match[str]) -> str:
            label = render_inline(match.group(1))
            href = html.escape(match.group(2).strip(), quote=True)
            external = href.startswith("http://") or href.startswith("https://")
            attrs = ' target="_blank" rel="noreferrer"' if external else ""
            return stash(f'<a href="{href}"{attrs}>{label}</a>')

        linked = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", replace_link, piece)
        escaped = html.escape(linked, quote=False)
        escaped = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", escaped)
        escaped = re.sub(
            r"(?<!\*)\*(?!\s)(.+?)(?<!\s)\*(?!\*)",
            r"<em>\1</em>",
            escaped,
        )

        for token, value in tokens.items():
            escaped = escaped.replace(token, value)

        rendered.append(escaped)

    return "".join(rendered)


def is_block_start(line: str) -> bool:
    stripped = line.strip()
    return bool(
        stripped.startswith("```")
        or re.match(r"#{1,6}\s+", stripped)
        or stripped.startswith(">")
        or re.match(r"[-*]\s+", stripped)
        or re.match(r"\d+\.\s+", stripped)
        or re.match(r"(-{3,}|\*{3,})$", stripped)
    )


def render_markdown(markdown_text: str) -> str:
    lines = markdown_text.splitlines()
    blocks: list[str] = []
    index = 0

    while index < len(lines):
        raw_line = lines[index]
        stripped = raw_line.strip()

        if not stripped:
            index += 1
            continue

        if stripped.startswith("```"):
            language = stripped[3:].strip()
            code_lines: list[str] = []
            index += 1
            while index < len(lines) and not lines[index].strip().startswith("```"):
                code_lines.append(lines[index])
                index += 1
            if index < len(lines):
                index += 1
            language_label = html.escape(language or "code", quote=True)
            language_attr = (
                f' class="language-{html.escape(language, quote=True)}"'
                if language
                else ""
            )
            blocks.append(
                f'<pre class="code-block" data-language="{language_label}"><code'
                f"{language_attr}>{html.escape(chr(10).join(code_lines))}</code></pre>"
            )
            continue

        heading_match = re.match(r"(#{1,6})\s+(.*)", stripped)
        if heading_match:
            level = len(heading_match.group(1))
            blocks.append(
                f"<h{level}>{render_inline(heading_match.group(2).strip())}</h{level}>"
            )
            index += 1
            continue

        if re.match(r"(-{3,}|\*{3,})$", stripped):
            blocks.append("<hr />")
            index += 1
            continue

        if stripped.startswith(">"):
            quote_lines: list[str] = []
            while index < len(lines) and lines[index].strip().startswith(">"):
                quote_lines.append(lines[index].strip()[1:].strip())
                index += 1
            quote_html = " ".join(render_inline(line) for line in quote_lines if line)
            blocks.append(f"<blockquote><p>{quote_html}</p></blockquote>")
            continue

        if re.match(r"[-*]\s+", stripped):
            items: list[str] = []
            while index < len(lines) and re.match(r"[-*]\s+", lines[index].strip()):
                item = re.sub(r"^[-*]\s+", "", lines[index].strip())
                items.append(f"<li>{render_inline(item)}</li>")
                index += 1
            blocks.append(f"<ul>{''.join(items)}</ul>")
            continue

        if re.match(r"\d+\.\s+", stripped):
            items = []
            while index < len(lines) and re.match(r"\d+\.\s+", lines[index].strip()):
                item = re.sub(r"^\d+\.\s+", "", lines[index].strip())
                items.append(f"<li>{render_inline(item)}</li>")
                index += 1
            blocks.append(f"<ol>{''.join(items)}</ol>")
            continue

        paragraph_lines = [stripped]
        index += 1
        while index < len(lines):
            candidate = lines[index]
            if not candidate.strip():
                break
            if is_block_start(candidate):
                break
            paragraph_lines.append(candidate.strip())
            index += 1
        blocks.append(f"<p>{render_inline(' '.join(paragraph_lines))}</p>")

    return "\n".join(blocks)


def load_posts() -> list[Post]:
    posts: list[Post] = []

    for path in sorted(CONTENT_DIR.glob("*.md")):
        raw_text = path.read_text(encoding="utf-8")
        front_matter, body = read_front_matter(raw_text)
        if front_matter.get("draft"):
            continue

        title = str(front_matter.get("title") or path.stem.replace("-", " ").title())
        raw_slug = str(
            front_matter.get("slug")
            or re.sub(r"^\d{4}-\d{2}-\d{2}-", "", path.stem)
        )
        slug = slugify(raw_slug)

        if not front_matter.get("date"):
            raise ValueError(f"Missing `date` in {path.relative_to(ROOT)}")

        post_date = date.fromisoformat(str(front_matter["date"]))
        tags = [str(tag) for tag in front_matter.get("tags", [])]
        summary = str(front_matter.get("summary") or derive_summary(body))
        body_html = render_markdown(body)

        posts.append(
            Post(
                source_path=path,
                slug=slug,
                title=title,
                summary=summary,
                body_markdown=body,
                body_html=body_html,
                date_value=post_date,
                tags=tags,
                featured=bool(front_matter.get("featured", False)),
                reading_time=max(1, math.ceil(word_count(body) / 220)),
            )
        )

    return sorted(
        posts,
        key=lambda post: (0 if post.featured else 1, -post.date_value.toordinal(), post.title),
    )


def render_page_header(profile: LandingProfile) -> str:
    return f"""
        <div class="rv r1">
            <div class="header">
                <div class="avatar-wrap">
                    <img class="avatar" src="{html.escape(profile.avatar_src, quote=True)}" alt="Avatar" loading="eager" />
                </div>
                <div class="title-wrap">
                    <h1 class="name">{html.escape(profile.name)}</h1>
                    <div class="tag">{profile.tag_html}</div>
                </div>
            </div>
        </div>
    """.strip()


def render_post_link(post: Post, href: str, muted: bool = False) -> str:
    class_name = "ml" if muted else "pl"
    arrow = "" if muted else inline_arrow()
    return f'<a href="{html.escape(href, quote=True)}" class="{class_name}">{html.escape(post.title)}{arrow}</a>'


def render_post_line(post: Post, href: str) -> str:
    return (
        f'<p><span class="meta-date">{format_long_date(post.date_value)}.</span> '
        f'{render_post_link(post, href)}'
        f' <span class="summary-sep">—</span> {html.escape(post.summary)}</p>'
    )


def render_command_palette(command_items: list[dict[str, str]]) -> str:
    items_html = []
    for item in command_items:
        items_html.append(
            f"""
            <a class="cmd-result" href="{html.escape(item['href'], quote=True)}" data-cmd-item data-search="{html.escape(item['search'], quote=True)}">
                <span class="cmd-result-label">{html.escape(item['label'])}</span>
                <span class="cmd-result-meta">{html.escape(item['meta'])}</span>
            </a>
            """.strip()
        )

    return f"""
        <div id="cmd-layer">
            <input type="text" id="cmd-input" class="cmd-input" placeholder="Jump somewhere..." autocomplete="off" spellcheck="false" />
            <div class="cmd-response" id="cmd-response">
                {''.join(items_html)}
                <p class="cmd-empty" id="cmd-empty" hidden>Can't match that one. But it's probably here.</p>
            </div>
        </div>
    """.strip()


def build_command_items(
    posts: list[Post],
    *,
    home_href: str,
    blog_href: str,
    archive_href: str,
    post_href_prefix: str,
) -> list[dict[str, str]]:
    items = [
        {
            "label": "Landing Page",
            "href": home_href,
            "meta": "home",
            "search": "landing home index pranav",
        },
        {
            "label": "Blog Home",
            "href": blog_href,
            "meta": "blog",
            "search": "blog writing notes index",
        },
        {
            "label": "Archive",
            "href": archive_href,
            "meta": "archive",
            "search": "archive all posts list",
        },
    ]

    for post in posts:
        items.append(
            {
                "label": post.title,
                "href": f"{post_href_prefix}{post.slug}.html",
                "meta": format_short_date(post.date_value),
                "search": " ".join(
                    [post.title, post.summary, format_short_date(post.date_value), *post.tags]
                ).lower(),
            }
        )

    return items


def page_shell(
    *,
    title: str,
    description: str,
    asset_prefix: str,
    command_items: list[dict[str, str]],
    content: str,
) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>{html.escape(title)} | {AUTHOR_NAME}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="{html.escape(description, quote=True)}" />
    <link rel="stylesheet" href="{html.escape(asset_prefix, quote=True)}/blog.css" />
</head>
<body>
    {GENERATED_COMMENT}
    <div class="page">
        {content}
    </div>
    {render_command_palette(command_items)}
    <script src="{html.escape(asset_prefix, quote=True)}/blog.js" defer></script>
</body>
</html>
"""


def render_index(posts: list[Post], profile: LandingProfile) -> str:
    latest_summary = posts[0].summary.rstrip(".!?") if posts else ""
    latest_line = (
        f"{render_post_link(posts[0], f'posts/{posts[0].slug}.html')} "
        f'<span class="summary-sep">—</span> {html.escape(latest_summary)}'
        if posts
        else "No posts yet. Add one in content/posts and rebuild."
    )
    post_lines = "\n".join(
        render_post_line(post, f"posts/{post.slug}.html") for post in posts
    )

    content = f"""
        {render_page_header(profile)}

        <div class="rv r2">
            <p>This is the longer room. Same palette, same pacing, just more space for notes that need more than a paragraph.</p>
            <p>Start here: {latest_line if posts else html.escape(latest_line)}. Visit the <a class="ml" href="archive.html">archive</a>. Or just <span class="cmdk" data-cmd-trigger>⌘K</span> and jump anywhere.</p>
        </div>

        <div class="rv r3">
            <p class="section-note">Recent notes.</p>
            {post_lines or '<p>No posts yet.</p>'}
        </div>
    """.strip()

    command_items = build_command_items(
        posts,
        home_href="../index.html",
        blog_href="index.html",
        archive_href="archive.html",
        post_href_prefix="posts/",
    )

    return page_shell(
        title=SITE_TITLE,
        description=SITE_DESCRIPTION,
        asset_prefix="assets",
        command_items=command_items,
        content=content,
    )


def render_archive(posts: list[Post], profile: LandingProfile) -> str:
    posts_by_year: dict[int, list[Post]] = {}
    for post in sorted(posts, key=lambda item: -item.date_value.toordinal()):
        posts_by_year.setdefault(post.date_value.year, []).append(post)

    sections: list[str] = []
    for year in sorted(posts_by_year, reverse=True):
        year_lines = "\n".join(
            render_post_line(post, f"posts/{post.slug}.html") for post in posts_by_year[year]
        )
        sections.append(f'<p class="section-note">{year}.</p>\n{year_lines}')

    content = f"""
        {render_page_header(profile)}

        <div class="rv r2">
            <p>The archive is everything in one pass. No cards. No chrome. Just dates, titles, and enough context to know where to go next.</p>
            <p>Back to the <a class="ml" href="index.html">blog home</a>, back to the <a class="ml" href="../index.html">landing page</a>, or <span class="cmdk" data-cmd-trigger>⌘K</span> if you'd rather move faster.</p>
        </div>

        <div class="rv r3">
            {''.join(sections) or '<p>No posts yet.</p>'}
        </div>
    """.strip()

    command_items = build_command_items(
        posts,
        home_href="../index.html",
        blog_href="index.html",
        archive_href="archive.html",
        post_href_prefix="posts/",
    )

    return page_shell(
        title="Archive",
        description="A chronological archive of every post.",
        asset_prefix="assets",
        command_items=command_items,
        content=content,
    )


def render_post_navigation(posts_by_date: list[Post], current_post: Post) -> str:
    ordered = sorted(posts_by_date, key=lambda item: -item.date_value.toordinal())
    current_index = next(
        index for index, post in enumerate(ordered) if post.slug == current_post.slug
    )

    newer = ordered[current_index - 1] if current_index > 0 else None
    older = ordered[current_index + 1] if current_index + 1 < len(ordered) else None

    parts: list[str] = []
    if newer:
        parts.append(f"Newer: {render_post_link(newer, newer.slug + '.html')}.")
    if older:
        parts.append(f"Older: {render_post_link(older, older.slug + '.html')}.")
    parts.append('Or back to the <a class="ml" href="../archive.html">archive</a>.')
    return f"<p>{' '.join(parts)}</p>"


def render_post_page(
    post: Post,
    all_posts: list[Post],
    profile: LandingProfile,
) -> str:
    tag_text = ", ".join(post.tags)
    meta_text = f"{format_long_date(post.date_value)} · {post.reading_time} min read"
    if tag_text:
        meta_text = f"{meta_text} · {tag_text}"

    content = f"""
        {render_page_header(profile)}

        <div class="rv r2">
            <p class="post-meta">{html.escape(meta_text)}</p>
            <h2 class="post-title">{html.escape(post.title)}</h2>
            <p>{html.escape(post.summary)}</p>
        </div>

        <div class="rv r3 article">
            {post.body_html}
            {render_post_navigation(all_posts, post)}
        </div>
    """.strip()

    command_items = build_command_items(
        all_posts,
        home_href="../../index.html",
        blog_href="../index.html",
        archive_href="../archive.html",
        post_href_prefix="",
    )

    return page_shell(
        title=post.title,
        description=post.summary,
        asset_prefix="../assets",
        command_items=command_items,
        content=content,
    )


def write_output(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def build_command_items_for_landing(posts: list[Post]) -> list[dict[str, str]]:
    items: list[dict[str, str]] = [
        {"label": "Home", "href": "index.html", "meta": "home", "search": "landing home index pranav"},
        {"label": "Blog", "href": "blog/index.html", "meta": "blog", "search": "blog writing notes index"},
        {"label": "Archive", "href": "blog/archive.html", "meta": "archive", "search": "archive all posts list"},
    ]
    for post in posts:
        items.append(
            {
                "label": post.title,
                "href": f"blog/posts/{post.slug}.html",
                "meta": format_short_date(post.date_value),
                "search": " ".join(
                    [post.title, post.summary, format_short_date(post.date_value), *post.tags]
                ).lower(),
            }
        )
    return items


def update_landing_command_palette(posts: list[Post]) -> None:
    landing_path = ROOT / "index.html"
    source = landing_path.read_text(encoding="utf-8")

    start_marker = "<!-- cmd-palette-start -->"
    end_marker = "<!-- cmd-palette-end -->"
    start = source.find(start_marker)
    end = source.find(end_marker)

    if start == -1 or end == -1:
        return

    command_items = build_command_items_for_landing(posts)

    items_html = []
    for item in command_items:
        items_html.append(
            f'            <a class="cmd-result" href="{html.escape(item["href"], quote=True)}" '
            f'data-cmd-item data-search="{html.escape(item["search"], quote=True)}">\n'
            f'                <span class="cmd-result-label">{html.escape(item["label"])}</span>\n'
            f'                <span class="cmd-result-meta">{html.escape(item["meta"])}</span>\n'
            f'            </a>'
        )

    palette_html = (
        '    <div id="cmd-layer">\n'
        '        <input type="text" id="cmd-input" class="cmd-input" placeholder="Jump somewhere..." autocomplete="off" spellcheck="false" />\n'
        '        <div class="cmd-response" id="cmd-response">\n'
        + "\n".join(items_html) + "\n"
        '            <p class="cmd-empty" id="cmd-empty" hidden>Can\'t match that one. But it\'s probably here.</p>\n'
        '        </div>\n'
        '    </div>'
    )

    new_source = (
        source[:start]
        + start_marker + "\n"
        + palette_html + "\n    "
        + end_marker
        + source[end + len(end_marker):]
    )
    landing_path.write_text(new_source, encoding="utf-8")


def build_site() -> list[Post]:
    BLOG_DIR.mkdir(parents=True, exist_ok=True)
    POSTS_DIR.mkdir(parents=True, exist_ok=True)

    posts = load_posts()
    profile = load_landing_profile()
    write_output(BLOG_DIR / "index.html", render_index(posts, profile))
    write_output(BLOG_DIR / "archive.html", render_archive(posts, profile))

    active_post_paths: set[Path] = set()
    for post in posts:
        post_output_path = POSTS_DIR / f"{post.slug}.html"
        active_post_paths.add(post_output_path)
        write_output(post_output_path, render_post_page(post, posts, profile))

    for existing_post in POSTS_DIR.glob("*.html"):
        if existing_post not in active_post_paths:
            existing_post.unlink()

    update_landing_command_palette(posts)

    return posts


def create_new_post(title: str, requested_date: date | None = None) -> Path:
    post_date = requested_date or date.today()
    base_slug = slugify(title)
    filename = f"{post_date.isoformat()}-{base_slug}.md"
    target = CONTENT_DIR / filename
    suffix = 2

    while target.exists():
        target = CONTENT_DIR / f"{post_date.isoformat()}-{base_slug}-{suffix}.md"
        suffix += 1

    template = f"""---
title: {title}
date: {post_date.isoformat()}
summary: One line that will show up on the blog homepage.
tags: notes, draft
featured: false
---
Start writing here.
"""
    target.write_text(template, encoding="utf-8")
    return target


def serve_site(port: int) -> None:
    build_site()

    class BlogHandler(SimpleHTTPRequestHandler):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, directory=str(ROOT), **kwargs)

        def do_GET(self) -> None:  # noqa: N802
            try:
                build_site()
            except Exception as exc:  # pragma: no cover - manual workflow helper
                self.send_response(500)
                self.send_header("Content-Type", "text/plain; charset=utf-8")
                self.end_headers()
                self.wfile.write(str(exc).encode("utf-8"))
                return
            super().do_GET()

    server = ThreadingHTTPServer(("127.0.0.1", port), BlogHandler)
    print(f"Serving on http://127.0.0.1:{port}/blog/")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopping server.")
    finally:
        server.server_close()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Scaffold, build, and preview the blog beside index.html."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    build_parser = subparsers.add_parser("build", help="Generate the blog HTML files.")
    build_parser.set_defaults(command_name="build")

    new_parser = subparsers.add_parser("new", help="Create a new markdown post.")
    new_parser.add_argument("title", help="Title for the new post")
    new_parser.add_argument(
        "--date",
        dest="date_value",
        type=date.fromisoformat,
        help="Optional publish date in YYYY-MM-DD format",
    )

    serve_parser = subparsers.add_parser(
        "serve",
        help="Build the blog and serve the whole site locally.",
    )
    serve_parser.add_argument(
        "--port",
        type=int,
        default=8000,
        help="Port to serve on. Defaults to 8000.",
    )

    return parser


def main() -> int:
    CONTENT_DIR.mkdir(parents=True, exist_ok=True)
    parser = build_parser()
    args = parser.parse_args()

    try:
        if args.command == "build":
            posts = build_site()
            print(f"Built {len(posts)} post(s) into {BLOG_DIR.relative_to(ROOT)}.")
            return 0

        if args.command == "new":
            target = create_new_post(args.title, args.date_value)
            print(target.relative_to(ROOT))
            return 0

        if args.command == "serve":
            serve_site(args.port)
            return 0
    except Exception as exc:  # pragma: no cover - surfaced to CLI
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
